/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};

/* quadrotor_ned_expl_ode_fun:(i0[13],i1[4],i2[4])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=5.0000000000000000e-01;
  a01=arg[0]? arg[0][10] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][4] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][11] : 0;
  a06=(a00*a05);
  a07=arg[0]? arg[0][5] : 0;
  a08=(a06*a07);
  a04=(a04+a08);
  a08=arg[0]? arg[0][12] : 0;
  a00=(a00*a08);
  a09=arg[0]? arg[0][6] : 0;
  a10=(a00*a09);
  a04=(a04+a10);
  a04=(-a04);
  if (res[0]!=0) res[0][3]=a04;
  a04=arg[0]? arg[0][3] : 0;
  a10=(a02*a04);
  a11=(a00*a07);
  a10=(a10+a11);
  a11=(a06*a09);
  a10=(a10-a11);
  if (res[0]!=0) res[0][4]=a10;
  a10=(a06*a04);
  a11=(a00*a03);
  a10=(a10-a11);
  a11=(a02*a09);
  a10=(a10+a11);
  if (res[0]!=0) res[0][5]=a10;
  a00=(a00*a04);
  a06=(a06*a03);
  a00=(a00+a06);
  a02=(a02*a07);
  a00=(a00-a02);
  if (res[0]!=0) res[0][6]=a00;
  a00=2.;
  a02=(a00*a03);
  a06=(a02*a09);
  a10=(a00*a07);
  a11=(a10*a04);
  a06=(a06+a11);
  a11=arg[1]? arg[1][0] : 0;
  a06=(a06*a11);
  a12=1.2869999999999999e+00;
  a06=(a06/a12);
  a06=(-a06);
  if (res[0]!=0) res[0][7]=a06;
  a10=(a10*a09);
  a02=(a02*a04);
  a10=(a10-a02);
  a10=(a10*a11);
  a10=(a10/a12);
  a10=(-a10);
  if (res[0]!=0) res[0][8]=a10;
  a10=1.2601480319999999e+01;
  a02=1.;
  a03=casadi_sq(a03);
  a03=(a00*a03);
  a02=(a02-a03);
  a07=casadi_sq(a07);
  a00=(a00*a07);
  a02=(a02-a00);
  a02=(a02*a11);
  a10=(a10-a02);
  a10=(a10/a12);
  if (res[0]!=0) res[0][9]=a10;
  a10=2.4038461538461542e+02;
  a12=arg[1]? arg[1][1] : 0;
  a02=5.5440000000000003e-03;
  a02=(a02*a08);
  a11=(a05*a02);
  a00=4.8549999999999999e-03;
  a00=(a00*a05);
  a07=(a08*a00);
  a11=(a11-a07);
  a12=(a12-a11);
  a10=(a10*a12);
  if (res[0]!=0) res[0][10]=a10;
  a10=2.0597322348094747e+02;
  a12=arg[1]? arg[1][2] : 0;
  a11=4.1599999999999996e-03;
  a11=(a11*a01);
  a08=(a08*a11);
  a02=(a01*a02);
  a08=(a08-a02);
  a12=(a12-a08);
  a10=(a10*a12);
  if (res[0]!=0) res[0][11]=a10;
  a10=1.8037518037518038e+02;
  a12=arg[1]? arg[1][3] : 0;
  a01=(a01*a00);
  a05=(a05*a11);
  a01=(a01-a05);
  a12=(a12-a01);
  a10=(a10*a12);
  if (res[0]!=0) res[0][12]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
