/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};

/* quadrotor_ned_expl_vde_adj:(i0[13],i1[13],i2[4],i3[4])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=2.;
  a01=arg[0]? arg[0][4] : 0;
  a02=(a00*a01);
  a03=arg[2]? arg[2][0] : 0;
  a04=7.7700077700077708e-01;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a04*a05);
  a06=(a03*a05);
  a07=(a02*a06);
  a08=arg[0]? arg[0][5] : 0;
  a09=(a00*a08);
  a10=arg[1]? arg[1][7] : 0;
  a10=(a04*a10);
  a11=(a03*a10);
  a12=(a09*a11);
  a07=(a07-a12);
  a12=5.0000000000000000e-01;
  a13=arg[0]? arg[0][12] : 0;
  a14=(a12*a13);
  a15=arg[1]? arg[1][6] : 0;
  a16=(a14*a15);
  a07=(a07+a16);
  a16=arg[0]? arg[0][11] : 0;
  a17=(a12*a16);
  a18=arg[1]? arg[1][5] : 0;
  a19=(a17*a18);
  a07=(a07+a19);
  a19=arg[0]? arg[0][10] : 0;
  a20=(a12*a19);
  a21=arg[1]? arg[1][4] : 0;
  a22=(a20*a21);
  a07=(a07+a22);
  if (res[0]!=0) res[0][3]=a07;
  a07=(a01+a01);
  a22=arg[1]? arg[1][9] : 0;
  a04=(a04*a22);
  a03=(a03*a04);
  a03=(a00*a03);
  a07=(a07*a03);
  a22=arg[0]? arg[0][3] : 0;
  a23=(a22*a06);
  a23=(a00*a23);
  a07=(a07+a23);
  a23=arg[0]? arg[0][6] : 0;
  a24=(a23*a11);
  a24=(a00*a24);
  a07=(a07-a24);
  a24=(a17*a15);
  a07=(a07+a24);
  a24=(a14*a18);
  a07=(a07-a24);
  a24=arg[1]? arg[1][3] : 0;
  a25=(a20*a24);
  a07=(a07-a25);
  if (res[0]!=0) res[0][4]=a07;
  a07=(a08+a08);
  a07=(a07*a03);
  a03=(a23*a06);
  a03=(a00*a03);
  a07=(a07-a03);
  a03=(a22*a11);
  a03=(a00*a03);
  a07=(a07-a03);
  a03=(a20*a15);
  a07=(a07-a03);
  a03=(a14*a21);
  a07=(a07+a03);
  a03=(a17*a24);
  a07=(a07-a03);
  if (res[0]!=0) res[0][5]=a07;
  a20=(a20*a18);
  a06=(a09*a06);
  a11=(a02*a11);
  a06=(a06+a11);
  a20=(a20-a06);
  a17=(a17*a21);
  a20=(a20-a17);
  a14=(a14*a24);
  a20=(a20-a14);
  if (res[0]!=0) res[0][6]=a20;
  a20=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a20;
  a20=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a20;
  a20=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a20;
  a20=5.5440000000000003e-03;
  a14=(a20*a13);
  a17=2.0597322348094747e+02;
  a06=arg[1]? arg[1][11] : 0;
  a17=(a17*a06);
  a06=(a14*a17);
  a11=4.8549999999999999e-03;
  a07=(a11*a16);
  a03=1.8037518037518038e+02;
  a25=arg[1]? arg[1][12] : 0;
  a03=(a03*a25);
  a25=(a07*a03);
  a06=(a06-a25);
  a25=4.1599999999999996e-03;
  a26=(a16*a03);
  a27=(a13*a17);
  a26=(a26-a27);
  a26=(a25*a26);
  a06=(a06+a26);
  a26=(a08*a15);
  a26=(a12*a26);
  a06=(a06-a26);
  a26=(a23*a18);
  a26=(a12*a26);
  a06=(a06+a26);
  a26=(a22*a21);
  a26=(a12*a26);
  a06=(a06+a26);
  a26=(a01*a24);
  a26=(a12*a26);
  a06=(a06-a26);
  if (res[0]!=0) res[0][10]=a06;
  a25=(a25*a19);
  a06=(a25*a03);
  a26=2.4038461538461542e+02;
  a27=arg[1]? arg[1][10] : 0;
  a26=(a26*a27);
  a13=(a13*a26);
  a27=(a19*a03);
  a13=(a13-a27);
  a11=(a11*a13);
  a06=(a06+a11);
  a14=(a14*a26);
  a06=(a06-a14);
  a14=(a01*a15);
  a14=(a12*a14);
  a06=(a06+a14);
  a14=(a22*a18);
  a14=(a12*a14);
  a06=(a06+a14);
  a14=(a23*a21);
  a14=(a12*a14);
  a06=(a06-a14);
  a14=(a08*a24);
  a14=(a12*a14);
  a06=(a06-a14);
  if (res[0]!=0) res[0][11]=a06;
  a07=(a07*a26);
  a25=(a25*a17);
  a07=(a07-a25);
  a19=(a19*a17);
  a16=(a16*a26);
  a19=(a19-a16);
  a20=(a20*a19);
  a07=(a07+a20);
  a15=(a22*a15);
  a15=(a12*a15);
  a07=(a07+a15);
  a18=(a01*a18);
  a18=(a12*a18);
  a07=(a07-a18);
  a21=(a08*a21);
  a21=(a12*a21);
  a07=(a07+a21);
  a24=(a23*a24);
  a12=(a12*a24);
  a07=(a07-a12);
  if (res[0]!=0) res[0][12]=a07;
  a07=1.;
  a01=casadi_sq(a01);
  a01=(a00*a01);
  a07=(a07-a01);
  a08=casadi_sq(a08);
  a00=(a00*a08);
  a07=(a07-a00);
  a07=(a07*a04);
  a04=(a09*a23);
  a00=(a02*a22);
  a04=(a04-a00);
  a04=(a04*a05);
  a07=(a07+a04);
  a02=(a02*a23);
  a09=(a09*a22);
  a02=(a02+a09);
  a02=(a02*a10);
  a07=(a07+a02);
  a07=(-a07);
  if (res[0]!=0) res[0][13]=a07;
  if (res[0]!=0) res[0][14]=a26;
  if (res[0]!=0) res[0][15]=a17;
  if (res[0]!=0) res[0][16]=a03;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
