/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ned_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[36] = 
  {17, 17, 0, 0, 0, 0, 0, 0,
  0, 0, 4, 8, 12, 16, 16, 16,
  16, 16, 16, 16, 7, 8, 9, 10,
  7, 8, 9, 10, 7, 8, 9, 10,
  7, 8, 9, 10};

/* quadrotor_ned_cost_y_hess:(i0[13],i1[4],i2[0],i3[8],i4[],i5[4])->(o0[17x17,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=arg[0]? arg[0][6] : 0;
  a01=2.;
  a02=1.;
  a03=arg[0]? arg[0][5] : 0;
  a04=casadi_sq(a03);
  a05=casadi_sq(a00);
  a04=(a04+a05);
  a04=(a01*a04);
  a02=(a02-a04);
  a04=arg[0]? arg[0][3] : 0;
  a05=(a04*a00);
  a06=arg[0]? arg[0][4] : 0;
  a07=(a06*a03);
  a05=(a05+a07);
  a05=(a01*a05);
  a07=casadi_sq(a05);
  a08=casadi_sq(a02);
  a07=(a07+a08);
  a08=(a02/a07);
  a09=atan2(a05,a02);
  a10=arg[5]? arg[5][3] : 0;
  a09=(a09-a10);
  a10=sin(a09);
  a11=arg[3]? arg[3][3] : 0;
  a12=(a10*a11);
  a09=cos(a09);
  a13=(a01*a00);
  a14=(a08*a13);
  a15=(a09*a14);
  a16=(a12*a15);
  a15=(a11*a15);
  a15=(a10*a15);
  a16=(a16+a15);
  a15=(a09*a11);
  a14=(a10*a14);
  a17=(a15*a14);
  a14=(a11*a14);
  a14=(a09*a14);
  a17=(a17+a14);
  a16=(a16-a17);
  a16=(a08*a16);
  a17=(a10*a12);
  a14=(a09*a15);
  a17=(a17+a14);
  a14=(a08/a07);
  a18=(a05+a05);
  a13=(a18*a13);
  a13=(a14*a13);
  a13=(a17*a13);
  a16=(a16-a13);
  a16=(a01*a16);
  a16=(a00*a16);
  if (res[0]!=0) res[0][0]=a16;
  a16=(a01*a03);
  a13=(a08*a16);
  a19=(a09*a13);
  a20=(a12*a19);
  a19=(a11*a19);
  a19=(a10*a19);
  a20=(a20+a19);
  a13=(a10*a13);
  a19=(a15*a13);
  a13=(a11*a13);
  a13=(a09*a13);
  a19=(a19+a13);
  a20=(a20-a19);
  a20=(a08*a20);
  a16=(a18*a16);
  a16=(a14*a16);
  a16=(a17*a16);
  a20=(a20-a16);
  a20=(a01*a20);
  a16=(a00*a20);
  if (res[0]!=0) res[0][1]=a16;
  a19=(a01*a06);
  a13=(a08*a19);
  a05=(a05/a07);
  a21=(a03+a03);
  a22=(a01*a21);
  a23=(a05*a22);
  a13=(a13+a23);
  a23=(a09*a13);
  a24=(a12*a23);
  a23=(a11*a23);
  a23=(a10*a23);
  a24=(a24+a23);
  a13=(a10*a13);
  a23=(a15*a13);
  a13=(a11*a13);
  a13=(a09*a13);
  a23=(a23+a13);
  a24=(a24-a23);
  a23=(a08*a24);
  a13=(a22/a07);
  a25=(a18*a19);
  a02=(a02+a02);
  a22=(a02*a22);
  a25=(a25-a22);
  a22=(a14*a25);
  a13=(a13+a22);
  a13=(a17*a13);
  a23=(a23-a13);
  a23=(a01*a23);
  a13=(a00*a23);
  if (res[0]!=0) res[0][2]=a13;
  a22=(a08*a17);
  a22=(a01*a22);
  a26=(a01*a04);
  a27=(a08*a26);
  a28=(a00+a00);
  a29=(a01*a28);
  a30=(a05*a29);
  a27=(a27+a30);
  a30=(a09*a27);
  a12=(a12*a30);
  a30=(a11*a30);
  a30=(a10*a30);
  a12=(a12+a30);
  a10=(a10*a27);
  a15=(a15*a10);
  a11=(a11*a10);
  a09=(a09*a11);
  a15=(a15+a09);
  a12=(a12-a15);
  a08=(a08*a12);
  a15=(a29/a07);
  a18=(a18*a26);
  a02=(a02*a29);
  a18=(a18-a02);
  a14=(a14*a18);
  a15=(a15+a14);
  a15=(a17*a15);
  a08=(a08-a15);
  a08=(a01*a08);
  a00=(a00*a08);
  a00=(a22+a00);
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a16;
  a20=(a03*a20);
  if (res[0]!=0) res[0][5]=a20;
  a20=(a03*a23);
  a22=(a22+a20);
  if (res[0]!=0) res[0][6]=a22;
  a03=(a03*a08);
  if (res[0]!=0) res[0][7]=a03;
  if (res[0]!=0) res[0][8]=a13;
  if (res[0]!=0) res[0][9]=a22;
  a22=(a05*a17);
  a22=(a01*a22);
  a22=(a01*a22);
  a19=(a19/a07);
  a13=(a05/a07);
  a25=(a13*a25);
  a19=(a19-a25);
  a19=(a17*a19);
  a24=(a05*a24);
  a19=(a19+a24);
  a19=(a01*a19);
  a19=(a21*a19);
  a19=(a22+a19);
  a23=(a06*a23);
  a19=(a19+a23);
  if (res[0]!=0) res[0][10]=a19;
  a26=(a26/a07);
  a13=(a13*a18);
  a26=(a26-a13);
  a17=(a17*a26);
  a05=(a05*a12);
  a17=(a17+a05);
  a01=(a01*a17);
  a21=(a21*a01);
  a06=(a06*a08);
  a21=(a21+a06);
  if (res[0]!=0) res[0][11]=a21;
  if (res[0]!=0) res[0][12]=a00;
  if (res[0]!=0) res[0][13]=a03;
  if (res[0]!=0) res[0][14]=a21;
  a28=(a28*a01);
  a22=(a22+a28);
  a04=(a04*a08);
  a22=(a22+a04);
  if (res[0]!=0) res[0][15]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ned_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ned_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ned_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ned_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ned_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ned_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
