/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};

/* holybro_expl_vde_adj:(i0[9],i1[9],i2[4],i3[0])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a01=cos(a00);
  a02=arg[2]? arg[2][2] : 0;
  a03=arg[1]? arg[1][8] : 0;
  a04=arg[0]? arg[0][7] : 0;
  a05=cos(a04);
  a06=(a03/a05);
  a07=(a02*a06);
  a08=arg[2]? arg[2][3] : 0;
  a09=arg[1]? arg[1][7] : 0;
  a10=(a08*a09);
  a07=(a07-a10);
  a10=tan(a04);
  a11=arg[1]? arg[1][6] : 0;
  a10=(a10*a11);
  a12=(a02*a10);
  a07=(a07+a12);
  a12=arg[0]? arg[0][8] : 0;
  a13=cos(a12);
  a14=arg[2]? arg[2][0] : 0;
  a15=1.2869999999999999e+00;
  a14=(a14/a15);
  a15=arg[1]? arg[1][4] : 0;
  a16=(a14*a15);
  a17=(a13*a16);
  a07=(a07-a17);
  a12=sin(a12);
  a17=arg[1]? arg[1][3] : 0;
  a18=(a14*a17);
  a19=(a12*a18);
  a07=(a07+a19);
  a07=(a01*a07);
  a00=sin(a00);
  a19=(a08*a06);
  a20=(a02*a09);
  a19=(a19+a20);
  a20=(a08*a10);
  a19=(a19+a20);
  a20=arg[1]? arg[1][5] : 0;
  a14=(a14*a20);
  a21=(a05*a14);
  a19=(a19+a21);
  a04=sin(a04);
  a21=(a12*a16);
  a22=(a04*a21);
  a19=(a19+a22);
  a22=(a13*a18);
  a23=(a04*a22);
  a19=(a19+a23);
  a19=(a00*a19);
  a07=(a07-a19);
  if (res[0]!=0) res[0][6]=a07;
  a08=(a08*a01);
  a07=(a08*a11);
  a02=(a02*a00);
  a19=(a02*a11);
  a07=(a07+a19);
  a19=casadi_sq(a05);
  a07=(a07/a19);
  a14=(a01*a14);
  a08=(a08/a05);
  a08=(a08/a05);
  a08=(a08*a03);
  a02=(a02/a05);
  a02=(a02/a05);
  a02=(a02*a03);
  a08=(a08+a02);
  a14=(a14-a08);
  a14=(a04*a14);
  a07=(a07-a14);
  a21=(a01*a21);
  a22=(a01*a22);
  a21=(a21+a22);
  a21=(a05*a21);
  a07=(a07+a21);
  if (res[0]!=0) res[0][7]=a07;
  a04=(a01*a04);
  a07=(a04*a16);
  a21=(a00*a18);
  a07=(a07+a21);
  a07=(a13*a07);
  a18=(a04*a18);
  a16=(a00*a16);
  a18=(a18-a16);
  a18=(a12*a18);
  a07=(a07-a18);
  if (res[0]!=0) res[0][8]=a07;
  a07=7.7700077700077708e-01;
  a05=(a01*a05);
  a05=(a05*a20);
  a05=(a07*a05);
  a20=(a04*a12);
  a18=(a00*a13);
  a20=(a20-a18);
  a20=(a20*a15);
  a20=(a07*a20);
  a05=(a05+a20);
  a04=(a04*a13);
  a12=(a00*a12);
  a04=(a04+a12);
  a04=(a04*a17);
  a07=(a07*a04);
  a05=(a05+a07);
  if (res[0]!=0) res[0][9]=a05;
  if (res[0]!=0) res[0][10]=a11;
  a11=(a00*a06);
  a05=(a01*a09);
  a11=(a11+a05);
  a05=(a00*a10);
  a11=(a11+a05);
  if (res[0]!=0) res[0][11]=a11;
  a06=(a01*a06);
  a00=(a00*a09);
  a06=(a06-a00);
  a01=(a01*a10);
  a06=(a06+a01);
  if (res[0]!=0) res[0][12]=a06;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int holybro_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real holybro_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
