/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {9, 9, 1};
static const casadi_int casadi_s2[3] = {9, 4, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* holybro_expl_vde_forw:(i0[9],i1[9x9],i2[9x4],i3[4],i4[0])->(o0[9],o1[9x9],o2[9x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[3]? arg[3][0] : 0;
  a01=1.2869999999999999e+00;
  a00=(a00/a01);
  a01=arg[0]? arg[0][6] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][7] : 0;
  a04=sin(a03);
  a05=(a02*a04);
  a06=arg[0]? arg[0][8] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a01=sin(a01);
  a06=sin(a06);
  a09=(a01*a06);
  a08=(a08+a09);
  a09=(a00*a08);
  if (res[0]!=0) res[0][3]=a09;
  a09=(a05*a06);
  a10=(a01*a07);
  a09=(a09-a10);
  a10=(a00*a09);
  if (res[0]!=0) res[0][4]=a10;
  a10=cos(a03);
  a11=(a02*a10);
  a12=(a00*a11);
  a13=9.7913599999999992e+00;
  a12=(a12-a13);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[3]? arg[3][1] : 0;
  a13=arg[3]? arg[3][2] : 0;
  a14=(a13*a01);
  a03=tan(a03);
  a15=(a14*a03);
  a12=(a12+a15);
  a15=arg[3]? arg[3][3] : 0;
  a16=(a15*a02);
  a17=(a16*a03);
  a12=(a12+a17);
  if (res[0]!=0) res[0][6]=a12;
  a12=(a13*a02);
  a17=(a15*a01);
  a12=(a12-a17);
  if (res[0]!=0) res[0][7]=a12;
  a12=(a14/a10);
  a17=(a16/a10);
  a18=(a12+a17);
  if (res[0]!=0) res[0][8]=a18;
  a18=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a18;
  a18=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a18;
  a18=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a18;
  a18=arg[1]? arg[1][7] : 0;
  a19=(a10*a18);
  a19=(a02*a19);
  a20=arg[1]? arg[1][6] : 0;
  a21=(a01*a20);
  a22=(a04*a21);
  a19=(a19-a22);
  a22=(a07*a19);
  a23=arg[1]? arg[1][8] : 0;
  a24=(a06*a23);
  a25=(a05*a24);
  a22=(a22-a25);
  a20=(a02*a20);
  a25=(a06*a20);
  a23=(a07*a23);
  a26=(a01*a23);
  a25=(a25+a26);
  a22=(a22+a25);
  a22=(a00*a22);
  if (res[1]!=0) res[1][3]=a22;
  a19=(a06*a19);
  a23=(a05*a23);
  a19=(a19+a23);
  a23=(a07*a20);
  a24=(a01*a24);
  a23=(a23-a24);
  a19=(a19-a23);
  a19=(a00*a19);
  if (res[1]!=0) res[1][4]=a19;
  a19=(a10*a21);
  a23=(a04*a18);
  a24=(a02*a23);
  a19=(a19+a24);
  a19=(a00*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][5]=a19;
  a19=(a13*a20);
  a24=(a03*a19);
  a22=casadi_sq(a10);
  a18=(a18/a22);
  a25=(a14*a18);
  a24=(a24+a25);
  a18=(a16*a18);
  a25=(a15*a21);
  a26=(a03*a25);
  a18=(a18-a26);
  a24=(a24+a18);
  if (res[1]!=0) res[1][6]=a24;
  a21=(a13*a21);
  a20=(a15*a20);
  a21=(a21+a20);
  a21=(-a21);
  if (res[1]!=0) res[1][7]=a21;
  a19=(a19/a10);
  a12=(a12/a10);
  a21=(a12*a23);
  a19=(a19+a21);
  a17=(a17/a10);
  a23=(a17*a23);
  a25=(a25/a10);
  a23=(a23-a25);
  a19=(a19+a23);
  if (res[1]!=0) res[1][8]=a19;
  a19=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a19;
  a19=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a19;
  a19=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][11]=a19;
  a19=arg[1]? arg[1][16] : 0;
  a23=(a10*a19);
  a23=(a02*a23);
  a25=arg[1]? arg[1][15] : 0;
  a21=(a01*a25);
  a20=(a04*a21);
  a23=(a23-a20);
  a20=(a07*a23);
  a24=arg[1]? arg[1][17] : 0;
  a18=(a06*a24);
  a26=(a05*a18);
  a20=(a20-a26);
  a25=(a02*a25);
  a26=(a06*a25);
  a24=(a07*a24);
  a27=(a01*a24);
  a26=(a26+a27);
  a20=(a20+a26);
  a20=(a00*a20);
  if (res[1]!=0) res[1][12]=a20;
  a23=(a06*a23);
  a24=(a05*a24);
  a23=(a23+a24);
  a24=(a07*a25);
  a18=(a01*a18);
  a24=(a24-a18);
  a23=(a23-a24);
  a23=(a00*a23);
  if (res[1]!=0) res[1][13]=a23;
  a23=(a10*a21);
  a24=(a04*a19);
  a18=(a02*a24);
  a23=(a23+a18);
  a23=(a00*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][14]=a23;
  a23=(a13*a25);
  a18=(a03*a23);
  a19=(a19/a22);
  a20=(a14*a19);
  a18=(a18+a20);
  a19=(a16*a19);
  a20=(a15*a21);
  a26=(a03*a20);
  a19=(a19-a26);
  a18=(a18+a19);
  if (res[1]!=0) res[1][15]=a18;
  a21=(a13*a21);
  a25=(a15*a25);
  a21=(a21+a25);
  a21=(-a21);
  if (res[1]!=0) res[1][16]=a21;
  a23=(a23/a10);
  a21=(a12*a24);
  a23=(a23+a21);
  a24=(a17*a24);
  a20=(a20/a10);
  a24=(a24-a20);
  a23=(a23+a24);
  if (res[1]!=0) res[1][17]=a23;
  a23=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a23;
  a23=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][19]=a23;
  a23=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][20]=a23;
  a23=arg[1]? arg[1][25] : 0;
  a24=(a10*a23);
  a24=(a02*a24);
  a20=arg[1]? arg[1][24] : 0;
  a21=(a01*a20);
  a25=(a04*a21);
  a24=(a24-a25);
  a25=(a07*a24);
  a18=arg[1]? arg[1][26] : 0;
  a19=(a06*a18);
  a26=(a05*a19);
  a25=(a25-a26);
  a20=(a02*a20);
  a26=(a06*a20);
  a18=(a07*a18);
  a27=(a01*a18);
  a26=(a26+a27);
  a25=(a25+a26);
  a25=(a00*a25);
  if (res[1]!=0) res[1][21]=a25;
  a24=(a06*a24);
  a18=(a05*a18);
  a24=(a24+a18);
  a18=(a07*a20);
  a19=(a01*a19);
  a18=(a18-a19);
  a24=(a24-a18);
  a24=(a00*a24);
  if (res[1]!=0) res[1][22]=a24;
  a24=(a10*a21);
  a18=(a04*a23);
  a19=(a02*a18);
  a24=(a24+a19);
  a24=(a00*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][23]=a24;
  a24=(a13*a20);
  a19=(a03*a24);
  a23=(a23/a22);
  a25=(a14*a23);
  a19=(a19+a25);
  a23=(a16*a23);
  a25=(a15*a21);
  a26=(a03*a25);
  a23=(a23-a26);
  a19=(a19+a23);
  if (res[1]!=0) res[1][24]=a19;
  a21=(a13*a21);
  a20=(a15*a20);
  a21=(a21+a20);
  a21=(-a21);
  if (res[1]!=0) res[1][25]=a21;
  a24=(a24/a10);
  a21=(a12*a18);
  a24=(a24+a21);
  a18=(a17*a18);
  a25=(a25/a10);
  a18=(a18-a25);
  a24=(a24+a18);
  if (res[1]!=0) res[1][26]=a24;
  a24=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][27]=a24;
  a24=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][28]=a24;
  a24=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][29]=a24;
  a24=arg[1]? arg[1][34] : 0;
  a18=(a10*a24);
  a18=(a02*a18);
  a25=arg[1]? arg[1][33] : 0;
  a21=(a01*a25);
  a20=(a04*a21);
  a18=(a18-a20);
  a20=(a07*a18);
  a19=arg[1]? arg[1][35] : 0;
  a23=(a06*a19);
  a26=(a05*a23);
  a20=(a20-a26);
  a25=(a02*a25);
  a26=(a06*a25);
  a19=(a07*a19);
  a27=(a01*a19);
  a26=(a26+a27);
  a20=(a20+a26);
  a20=(a00*a20);
  if (res[1]!=0) res[1][30]=a20;
  a18=(a06*a18);
  a19=(a05*a19);
  a18=(a18+a19);
  a19=(a07*a25);
  a23=(a01*a23);
  a19=(a19-a23);
  a18=(a18-a19);
  a18=(a00*a18);
  if (res[1]!=0) res[1][31]=a18;
  a18=(a10*a21);
  a19=(a04*a24);
  a23=(a02*a19);
  a18=(a18+a23);
  a18=(a00*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][32]=a18;
  a18=(a13*a25);
  a23=(a03*a18);
  a24=(a24/a22);
  a20=(a14*a24);
  a23=(a23+a20);
  a24=(a16*a24);
  a20=(a15*a21);
  a26=(a03*a20);
  a24=(a24-a26);
  a23=(a23+a24);
  if (res[1]!=0) res[1][33]=a23;
  a21=(a13*a21);
  a25=(a15*a25);
  a21=(a21+a25);
  a21=(-a21);
  if (res[1]!=0) res[1][34]=a21;
  a18=(a18/a10);
  a21=(a12*a19);
  a18=(a18+a21);
  a19=(a17*a19);
  a20=(a20/a10);
  a19=(a19-a20);
  a18=(a18+a19);
  if (res[1]!=0) res[1][35]=a18;
  a18=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][36]=a18;
  a18=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a18;
  a18=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][38]=a18;
  a18=arg[1]? arg[1][43] : 0;
  a19=(a10*a18);
  a19=(a02*a19);
  a20=arg[1]? arg[1][42] : 0;
  a21=(a01*a20);
  a25=(a04*a21);
  a19=(a19-a25);
  a25=(a07*a19);
  a23=arg[1]? arg[1][44] : 0;
  a24=(a06*a23);
  a26=(a05*a24);
  a25=(a25-a26);
  a20=(a02*a20);
  a26=(a06*a20);
  a23=(a07*a23);
  a27=(a01*a23);
  a26=(a26+a27);
  a25=(a25+a26);
  a25=(a00*a25);
  if (res[1]!=0) res[1][39]=a25;
  a19=(a06*a19);
  a23=(a05*a23);
  a19=(a19+a23);
  a23=(a07*a20);
  a24=(a01*a24);
  a23=(a23-a24);
  a19=(a19-a23);
  a19=(a00*a19);
  if (res[1]!=0) res[1][40]=a19;
  a19=(a10*a21);
  a23=(a04*a18);
  a24=(a02*a23);
  a19=(a19+a24);
  a19=(a00*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][41]=a19;
  a19=(a13*a20);
  a24=(a03*a19);
  a18=(a18/a22);
  a25=(a14*a18);
  a24=(a24+a25);
  a18=(a16*a18);
  a25=(a15*a21);
  a26=(a03*a25);
  a18=(a18-a26);
  a24=(a24+a18);
  if (res[1]!=0) res[1][42]=a24;
  a21=(a13*a21);
  a20=(a15*a20);
  a21=(a21+a20);
  a21=(-a21);
  if (res[1]!=0) res[1][43]=a21;
  a19=(a19/a10);
  a21=(a12*a23);
  a19=(a19+a21);
  a23=(a17*a23);
  a25=(a25/a10);
  a23=(a23-a25);
  a19=(a19+a23);
  if (res[1]!=0) res[1][44]=a19;
  a19=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][45]=a19;
  a19=arg[1]? arg[1][49] : 0;
  if (res[1]!=0) res[1][46]=a19;
  a19=arg[1]? arg[1][50] : 0;
  if (res[1]!=0) res[1][47]=a19;
  a19=arg[1]? arg[1][52] : 0;
  a23=(a10*a19);
  a23=(a02*a23);
  a25=arg[1]? arg[1][51] : 0;
  a21=(a01*a25);
  a20=(a04*a21);
  a23=(a23-a20);
  a20=(a07*a23);
  a24=arg[1]? arg[1][53] : 0;
  a18=(a06*a24);
  a26=(a05*a18);
  a20=(a20-a26);
  a25=(a02*a25);
  a26=(a06*a25);
  a24=(a07*a24);
  a27=(a01*a24);
  a26=(a26+a27);
  a20=(a20+a26);
  a20=(a00*a20);
  if (res[1]!=0) res[1][48]=a20;
  a23=(a06*a23);
  a24=(a05*a24);
  a23=(a23+a24);
  a24=(a07*a25);
  a18=(a01*a18);
  a24=(a24-a18);
  a23=(a23-a24);
  a23=(a00*a23);
  if (res[1]!=0) res[1][49]=a23;
  a23=(a10*a21);
  a24=(a04*a19);
  a18=(a02*a24);
  a23=(a23+a18);
  a23=(a00*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][50]=a23;
  a23=(a13*a25);
  a18=(a03*a23);
  a19=(a19/a22);
  a20=(a14*a19);
  a18=(a18+a20);
  a19=(a16*a19);
  a20=(a15*a21);
  a26=(a03*a20);
  a19=(a19-a26);
  a18=(a18+a19);
  if (res[1]!=0) res[1][51]=a18;
  a21=(a13*a21);
  a25=(a15*a25);
  a21=(a21+a25);
  a21=(-a21);
  if (res[1]!=0) res[1][52]=a21;
  a23=(a23/a10);
  a21=(a12*a24);
  a23=(a23+a21);
  a24=(a17*a24);
  a20=(a20/a10);
  a24=(a24-a20);
  a23=(a23+a24);
  if (res[1]!=0) res[1][53]=a23;
  a23=arg[1]? arg[1][57] : 0;
  if (res[1]!=0) res[1][54]=a23;
  a23=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][55]=a23;
  a23=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][56]=a23;
  a23=arg[1]? arg[1][61] : 0;
  a24=(a10*a23);
  a24=(a02*a24);
  a20=arg[1]? arg[1][60] : 0;
  a21=(a01*a20);
  a25=(a04*a21);
  a24=(a24-a25);
  a25=(a07*a24);
  a18=arg[1]? arg[1][62] : 0;
  a19=(a06*a18);
  a26=(a05*a19);
  a25=(a25-a26);
  a20=(a02*a20);
  a26=(a06*a20);
  a18=(a07*a18);
  a27=(a01*a18);
  a26=(a26+a27);
  a25=(a25+a26);
  a25=(a00*a25);
  if (res[1]!=0) res[1][57]=a25;
  a24=(a06*a24);
  a18=(a05*a18);
  a24=(a24+a18);
  a18=(a07*a20);
  a19=(a01*a19);
  a18=(a18-a19);
  a24=(a24-a18);
  a24=(a00*a24);
  if (res[1]!=0) res[1][58]=a24;
  a24=(a10*a21);
  a18=(a04*a23);
  a19=(a02*a18);
  a24=(a24+a19);
  a24=(a00*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][59]=a24;
  a24=(a13*a20);
  a19=(a03*a24);
  a23=(a23/a22);
  a25=(a14*a23);
  a19=(a19+a25);
  a23=(a16*a23);
  a25=(a15*a21);
  a26=(a03*a25);
  a23=(a23-a26);
  a19=(a19+a23);
  if (res[1]!=0) res[1][60]=a19;
  a21=(a13*a21);
  a20=(a15*a20);
  a21=(a21+a20);
  a21=(-a21);
  if (res[1]!=0) res[1][61]=a21;
  a24=(a24/a10);
  a21=(a12*a18);
  a24=(a24+a21);
  a18=(a17*a18);
  a25=(a25/a10);
  a18=(a18-a25);
  a24=(a24+a18);
  if (res[1]!=0) res[1][62]=a24;
  a24=arg[1]? arg[1][66] : 0;
  if (res[1]!=0) res[1][63]=a24;
  a24=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][64]=a24;
  a24=arg[1]? arg[1][68] : 0;
  if (res[1]!=0) res[1][65]=a24;
  a24=arg[1]? arg[1][70] : 0;
  a18=(a10*a24);
  a18=(a02*a18);
  a25=arg[1]? arg[1][69] : 0;
  a21=(a01*a25);
  a20=(a04*a21);
  a18=(a18-a20);
  a20=(a07*a18);
  a19=arg[1]? arg[1][71] : 0;
  a23=(a06*a19);
  a26=(a05*a23);
  a20=(a20-a26);
  a25=(a02*a25);
  a26=(a06*a25);
  a19=(a07*a19);
  a27=(a01*a19);
  a26=(a26+a27);
  a20=(a20+a26);
  a20=(a00*a20);
  if (res[1]!=0) res[1][66]=a20;
  a18=(a06*a18);
  a19=(a05*a19);
  a18=(a18+a19);
  a19=(a07*a25);
  a23=(a01*a23);
  a19=(a19-a23);
  a18=(a18-a19);
  a18=(a00*a18);
  if (res[1]!=0) res[1][67]=a18;
  a18=(a10*a21);
  a19=(a04*a24);
  a23=(a02*a19);
  a18=(a18+a23);
  a18=(a00*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][68]=a18;
  a18=(a13*a25);
  a23=(a03*a18);
  a24=(a24/a22);
  a20=(a14*a24);
  a23=(a23+a20);
  a24=(a16*a24);
  a20=(a15*a21);
  a26=(a03*a20);
  a24=(a24-a26);
  a23=(a23+a24);
  if (res[1]!=0) res[1][69]=a23;
  a21=(a13*a21);
  a25=(a15*a25);
  a21=(a21+a25);
  a21=(-a21);
  if (res[1]!=0) res[1][70]=a21;
  a18=(a18/a10);
  a21=(a12*a19);
  a18=(a18+a21);
  a19=(a17*a19);
  a20=(a20/a10);
  a19=(a19-a20);
  a18=(a18+a19);
  if (res[1]!=0) res[1][71]=a18;
  a18=arg[1]? arg[1][75] : 0;
  if (res[1]!=0) res[1][72]=a18;
  a18=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][73]=a18;
  a18=arg[1]? arg[1][77] : 0;
  if (res[1]!=0) res[1][74]=a18;
  a18=arg[1]? arg[1][79] : 0;
  a19=(a10*a18);
  a19=(a02*a19);
  a20=arg[1]? arg[1][78] : 0;
  a21=(a01*a20);
  a25=(a04*a21);
  a19=(a19-a25);
  a25=(a07*a19);
  a23=arg[1]? arg[1][80] : 0;
  a24=(a06*a23);
  a26=(a05*a24);
  a25=(a25-a26);
  a20=(a02*a20);
  a26=(a06*a20);
  a23=(a07*a23);
  a27=(a01*a23);
  a26=(a26+a27);
  a25=(a25+a26);
  a25=(a00*a25);
  if (res[1]!=0) res[1][75]=a25;
  a19=(a06*a19);
  a23=(a05*a23);
  a19=(a19+a23);
  a23=(a07*a20);
  a24=(a01*a24);
  a23=(a23-a24);
  a19=(a19-a23);
  a19=(a00*a19);
  if (res[1]!=0) res[1][76]=a19;
  a19=(a10*a21);
  a23=(a04*a18);
  a24=(a02*a23);
  a19=(a19+a24);
  a19=(a00*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][77]=a19;
  a19=(a13*a20);
  a24=(a03*a19);
  a18=(a18/a22);
  a25=(a14*a18);
  a24=(a24+a25);
  a18=(a16*a18);
  a25=(a15*a21);
  a26=(a03*a25);
  a18=(a18-a26);
  a24=(a24+a18);
  if (res[1]!=0) res[1][78]=a24;
  a21=(a13*a21);
  a20=(a15*a20);
  a21=(a21+a20);
  a21=(-a21);
  if (res[1]!=0) res[1][79]=a21;
  a19=(a19/a10);
  a21=(a12*a23);
  a19=(a19+a21);
  a23=(a17*a23);
  a25=(a25/a10);
  a23=(a23-a25);
  a19=(a19+a23);
  if (res[1]!=0) res[1][80]=a19;
  a19=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a19;
  a19=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a19;
  a19=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a19;
  a19=7.7700077700077708e-01;
  a08=(a19*a08);
  a23=arg[2]? arg[2][7] : 0;
  a25=(a10*a23);
  a25=(a02*a25);
  a21=arg[2]? arg[2][6] : 0;
  a20=(a01*a21);
  a24=(a04*a20);
  a25=(a25-a24);
  a24=(a07*a25);
  a18=arg[2]? arg[2][8] : 0;
  a26=(a06*a18);
  a27=(a05*a26);
  a24=(a24-a27);
  a21=(a02*a21);
  a27=(a06*a21);
  a18=(a07*a18);
  a28=(a01*a18);
  a27=(a27+a28);
  a24=(a24+a27);
  a24=(a00*a24);
  a08=(a08+a24);
  if (res[2]!=0) res[2][3]=a08;
  a09=(a19*a09);
  a25=(a06*a25);
  a18=(a05*a18);
  a25=(a25+a18);
  a18=(a07*a21);
  a26=(a01*a26);
  a18=(a18-a26);
  a25=(a25-a18);
  a25=(a00*a25);
  a09=(a09+a25);
  if (res[2]!=0) res[2][4]=a09;
  a19=(a19*a11);
  a11=(a10*a20);
  a09=(a04*a23);
  a25=(a02*a09);
  a11=(a11+a25);
  a11=(a00*a11);
  a19=(a19-a11);
  if (res[2]!=0) res[2][5]=a19;
  a19=(a13*a21);
  a11=(a03*a19);
  a23=(a23/a22);
  a25=(a14*a23);
  a11=(a11+a25);
  a23=(a16*a23);
  a25=(a15*a20);
  a18=(a03*a25);
  a23=(a23-a18);
  a11=(a11+a23);
  if (res[2]!=0) res[2][6]=a11;
  a20=(a13*a20);
  a21=(a15*a21);
  a20=(a20+a21);
  a20=(-a20);
  if (res[2]!=0) res[2][7]=a20;
  a19=(a19/a10);
  a20=(a12*a09);
  a19=(a19+a20);
  a09=(a17*a09);
  a25=(a25/a10);
  a09=(a09-a25);
  a19=(a19+a09);
  if (res[2]!=0) res[2][8]=a19;
  a19=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a19;
  a19=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a19;
  a19=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][11]=a19;
  a19=arg[2]? arg[2][16] : 0;
  a09=(a10*a19);
  a09=(a02*a09);
  a25=arg[2]? arg[2][15] : 0;
  a20=(a01*a25);
  a21=(a04*a20);
  a09=(a09-a21);
  a21=(a07*a09);
  a11=arg[2]? arg[2][17] : 0;
  a23=(a06*a11);
  a18=(a05*a23);
  a21=(a21-a18);
  a25=(a02*a25);
  a18=(a06*a25);
  a11=(a07*a11);
  a26=(a01*a11);
  a18=(a18+a26);
  a21=(a21+a18);
  a21=(a00*a21);
  if (res[2]!=0) res[2][12]=a21;
  a09=(a06*a09);
  a11=(a05*a11);
  a09=(a09+a11);
  a11=(a07*a25);
  a23=(a01*a23);
  a11=(a11-a23);
  a09=(a09-a11);
  a09=(a00*a09);
  if (res[2]!=0) res[2][13]=a09;
  a09=(a10*a20);
  a11=(a04*a19);
  a23=(a02*a11);
  a09=(a09+a23);
  a09=(a00*a09);
  a09=(-a09);
  if (res[2]!=0) res[2][14]=a09;
  a09=1.;
  a23=(a13*a25);
  a21=(a03*a23);
  a19=(a19/a22);
  a18=(a14*a19);
  a21=(a21+a18);
  a19=(a16*a19);
  a18=(a15*a20);
  a26=(a03*a18);
  a19=(a19-a26);
  a21=(a21+a19);
  a09=(a09+a21);
  if (res[2]!=0) res[2][15]=a09;
  a20=(a13*a20);
  a25=(a15*a25);
  a20=(a20+a25);
  a20=(-a20);
  if (res[2]!=0) res[2][16]=a20;
  a23=(a23/a10);
  a20=(a12*a11);
  a23=(a23+a20);
  a11=(a17*a11);
  a18=(a18/a10);
  a11=(a11-a18);
  a23=(a23+a11);
  if (res[2]!=0) res[2][17]=a23;
  a23=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a23;
  a23=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][19]=a23;
  a23=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][20]=a23;
  a23=arg[2]? arg[2][25] : 0;
  a11=(a10*a23);
  a11=(a02*a11);
  a18=arg[2]? arg[2][24] : 0;
  a20=(a01*a18);
  a25=(a04*a20);
  a11=(a11-a25);
  a25=(a07*a11);
  a09=arg[2]? arg[2][26] : 0;
  a21=(a06*a09);
  a19=(a05*a21);
  a25=(a25-a19);
  a18=(a02*a18);
  a19=(a06*a18);
  a09=(a07*a09);
  a26=(a01*a09);
  a19=(a19+a26);
  a25=(a25+a19);
  a25=(a00*a25);
  if (res[2]!=0) res[2][21]=a25;
  a11=(a06*a11);
  a09=(a05*a09);
  a11=(a11+a09);
  a09=(a07*a18);
  a21=(a01*a21);
  a09=(a09-a21);
  a11=(a11-a09);
  a11=(a00*a11);
  if (res[2]!=0) res[2][22]=a11;
  a11=(a10*a20);
  a09=(a04*a23);
  a21=(a02*a09);
  a11=(a11+a21);
  a11=(a00*a11);
  a11=(-a11);
  if (res[2]!=0) res[2][23]=a11;
  a11=(a03*a01);
  a21=(a13*a18);
  a25=(a03*a21);
  a23=(a23/a22);
  a19=(a14*a23);
  a25=(a25+a19);
  a23=(a16*a23);
  a19=(a15*a20);
  a26=(a03*a19);
  a23=(a23-a26);
  a25=(a25+a23);
  a11=(a11+a25);
  if (res[2]!=0) res[2][24]=a11;
  a20=(a13*a20);
  a18=(a15*a18);
  a20=(a20+a18);
  a20=(a02-a20);
  if (res[2]!=0) res[2][25]=a20;
  a20=(a01/a10);
  a21=(a21/a10);
  a18=(a12*a09);
  a21=(a21+a18);
  a09=(a17*a09);
  a19=(a19/a10);
  a09=(a09-a19);
  a21=(a21+a09);
  a20=(a20+a21);
  if (res[2]!=0) res[2][26]=a20;
  a20=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][27]=a20;
  a20=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][28]=a20;
  a20=arg[2]? arg[2][32] : 0;
  if (res[2]!=0) res[2][29]=a20;
  a20=arg[2]? arg[2][34] : 0;
  a21=(a10*a20);
  a21=(a02*a21);
  a09=arg[2]? arg[2][33] : 0;
  a19=(a01*a09);
  a18=(a04*a19);
  a21=(a21-a18);
  a18=(a07*a21);
  a11=arg[2]? arg[2][35] : 0;
  a25=(a06*a11);
  a23=(a05*a25);
  a18=(a18-a23);
  a09=(a02*a09);
  a23=(a06*a09);
  a11=(a07*a11);
  a26=(a01*a11);
  a23=(a23+a26);
  a18=(a18+a23);
  a18=(a00*a18);
  if (res[2]!=0) res[2][30]=a18;
  a06=(a06*a21);
  a05=(a05*a11);
  a06=(a06+a05);
  a07=(a07*a09);
  a25=(a01*a25);
  a07=(a07-a25);
  a06=(a06-a07);
  a06=(a00*a06);
  if (res[2]!=0) res[2][31]=a06;
  a06=(a10*a19);
  a04=(a04*a20);
  a07=(a02*a04);
  a06=(a06+a07);
  a00=(a00*a06);
  a00=(-a00);
  if (res[2]!=0) res[2][32]=a00;
  a00=(a03*a02);
  a06=(a13*a09);
  a07=(a03*a06);
  a20=(a20/a22);
  a14=(a14*a20);
  a07=(a07+a14);
  a16=(a16*a20);
  a20=(a15*a19);
  a03=(a03*a20);
  a16=(a16-a03);
  a07=(a07+a16);
  a00=(a00+a07);
  if (res[2]!=0) res[2][33]=a00;
  a13=(a13*a19);
  a15=(a15*a09);
  a13=(a13+a15);
  a01=(a01+a13);
  a01=(-a01);
  if (res[2]!=0) res[2][34]=a01;
  a02=(a02/a10);
  a06=(a06/a10);
  a12=(a12*a04);
  a06=(a06+a12);
  a17=(a17*a04);
  a20=(a20/a10);
  a17=(a17-a20);
  a06=(a06+a17);
  a02=(a02+a06);
  if (res[2]!=0) res[2][35]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int holybro_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real holybro_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
